export const APP_CONFIG = {
  APP_NAME: 'InfraPilot / BuildForce 360',
  API_BASE_URL: import.meta.env.VITE_API_URL || 'http://localhost:5000/api',
  STORAGE_KEYS: {
    TOKEN: 'civil_erp_token',
    USER: 'civil_erp_user',
    COMPANY: 'civil_erp_company',
    VIEWING_USER: 'infrapilot_viewing_user',
    SIDEBAR_WIDTH: 'infrapilot_sidebar_width',
    SIDEBAR_MINIMIZED: 'infrapilot_sidebar_minimized',
  },
  DEFAULT_ROLES: {
    SUPER_ADMIN: 'SUPER_ADMIN',
    ADMIN: 'ADMIN',
    SITE_ENGINEER: 'SITE_ENGINEER',
    PROJECT_MANAGER: 'PROJECT_MANAGER',
    SALES_MANAGER: 'SALES_MANAGER',
  },
  NAVIGATION_ICONS: [
    'Home',
    'Users',
    'HardHat',
    'Briefcase',
    'Settings',
    'Layers',
    'Link',
    'PieChart',
    'FileSpreadsheet',
    'Coins',
    'CreditCard',
    'Handshake',
    'CalendarRange',
    'BookOpen',
    'Calculator',
    'ClipboardCheck',
  ],
  ROLE_ACCENT_COLORS: ['#F59E0B', '#10B981', '#3B82F6', '#8B5CF6', '#EC4899', '#EF4444'],
} as const;
